const actions = {
    SET_NUMBER_OF_PLAYERS: 'SET_NUMBER_OF_PLAYERS',
    ADD_DAMAGE: 'ADD_DAMAGE',
    SUBTRACT_DAMAGE: 'SUBTRACT_DAMAGE',
    ADD_COMMANDER_DAMAGE: 'ADD_COMMANDER_DAMAGE',
    SUBTRACT_COMMANDER_DAMAGE: 'SUBTRACT_COMMANDER_DAMAGE',
    TOGGLE_MENU: 'TOGGLE_MENU',
    SET_MENU_ITEM: 'SET_MENU_ITEM',
    RESET_LIFE: 'RESET_LIFE'
}

export default actions;