const actions = {
    SET_NUMBER_OF_PLAYERS: 'SET_NUMBER_OF_PLAYERS',
    ADD_DAMAGE: 'ADD_DAMAGE',
    SUBTRACT_DAMAGE: 'SUBTRACT_DAMAGE',
    ADD_COMMANDER_DAMAGE: 'ADD_COMMANDER_DAMAGE',
    SUBTRACT_COMMANDER_DAMAGE: 'SUBTRACT_COMMANDER_DAMAGE',
    SET_MENU_OPEN: 'SET_MENU_OPEN',
    SET_MENU_ITEM: 'SET_MENU_ITEM',
    RESET_LIFE: 'RESET_LIFE',
    SWITCH_THEME: 'SWITCH_THEME',
    TOGGLE_BACKGROUND_ANIMATION: 'TOGGLE_BACKGROUND_ANIMATION'
}

export default actions;